export enum ActorDataState {
    NEW = "NEW",
    UPDATED_TO = "UPDATED_TO",
    UPDATED_FROM = "UPDATED_FROM",
    SENT = "SENT",
    PERSISTENT = "PERSISTENT",
    DELETED = "DELETED",
    CHECKED = "CHECKED",
    CHECK_FAILED = "CHECK_FAILED",
    ERROR_ADD = "ERROR_ADD",
    ERROR_CHECK = "ERROR_CHECK",
    ERROR_SEND = "ERROR_SEND",
    ERROR_DELETE = "ERROR_DELETE",
}
